quarkus:
  default-locale: pt_BR

  application:
    version: "1.0.0-SNAPSHOT"
    name: "desafio-back-end"
  
  http:
    root-path: "/api"
    cors:
      ~: true
      origins: "/.*/"
    
  smallrye-openapi:
    path: "/api/swagger"
    info-title: Desafio Back-end API
    info-version: 1.0.0
    info-description: Desafio proposto aos desenvolvedores back-end para ingresso na TEIA.
    info-contact-email: renato.f.lopes@caixa.gov.br
    info-contact-name: Renato Ferreira da Silva Lopes
    info-contact-url: https://github.com/renatoLopesCaixa
    info-license-name: MIT License
    info-license-url: https://www.mit.edu/~amini/LICENSE.md
    
  jacoco:
    report-location: "src/test/jacoco-report"

#para o desafio deixei o swagger-ui habilitado em prod    
  swagger-ui:
    always-include: true
    path: "/api/swagger-ui"

#log
"%dev":
  quarkus:
    log:
      level: DEBUG
"%test":
  quarkus:
    log:
      level: INFO
"%homol":
  quarkus:
    log:
      level: WARN
"%prod":
  quarkus:
    log:
      level: ERROR

greeting:
  message: "hello"
